-- Generated from seed/resources.json. Safe to rerun.

create extension if not exists pgcrypto;

create table if not exists public.collections (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  description text,
  is_research boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.resources (
  id uuid primary key default gen_random_uuid(),
  collection_id uuid not null references public.collections(id) on delete cascade,
  slug text not null unique,
  title text not null,
  type text not null check (type in ('book', 'paper', 'article', 'video', 'podcast', 'website')),
  url text,
  authors text[] not null default '{}',
  publisher text,
  published_date date,
  added_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  tags text[] not null default '{}',
  status text not null default 'unread' check (status in ('unread', 'reading', 'read')),
  date_read date,
  cliff_notes text,
  cliff_notes_model text,
  personal_notes text,
  cover_image_url text,
  source_domain text,
  is_essential boolean not null default false
);

create index if not exists resources_collection_id_idx on public.resources(collection_id);
create index if not exists resources_status_idx on public.resources(status);
create index if not exists resources_type_idx on public.resources(type);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists resources_set_updated_at on public.resources;
create trigger resources_set_updated_at
before update on public.resources
for each row
execute function public.set_updated_at();


-- Seed data from JSON
with seed as (
  select $seed$
{
  "_meta": {
    "description": "Seed dataset for Readable. Generated from the 'Learning, Teaching & AI' curated reading list (April 2026 planning conversation).",
    "notes": "cliff_notes here are brief curation seeds written during list compilation — suitable placeholders, intentionally short. For fuller notes, re-run resources through the ingestion pipeline after launch (drafts via INGEST_MODEL, then human review). published_date uses YYYY-01-01 when only the year is known; null for ongoing publications. All statuses default to 'unread' — the owner marks real reading history after import.",
    "schema_version": 1
  },
  "collections": [
    {
      "name": "Design × AI × Learning",
      "slug": "design-ai-learning",
      "description": "Research and expert opinion at the intersection of design, AI/LLMs, and K-12 teaching & learning. Foundations first: learning science, pedagogy, child development, and edtech history beneath the AI-era debate.",
      "is_research": true
    }
  ],
  "resources": [
    {
      "slug": "why-dont-students-like-school",
      "collection": "design-ai-learning",
      "title": "Why Don't Students Like School?",
      "type": "book",
      "url": "https://www.danielwillingham.com/why-dont-students-like-school.html",
      "authors": ["Daniel T. Willingham"],
      "publisher": "Jossey-Bass",
      "published_date": "2021-01-01",
      "tags": ["learning-science", "cognitive-science", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "A cognitive scientist explains nine principles of how the mind works and what they mean for classroom practice. The single most efficient way to get a grounded model of student cognition; nearly every good teacher book cites it.",
      "personal_notes": null
    },
    {
      "slug": "make-it-stick",
      "collection": "design-ai-learning",
      "title": "Make It Stick: The Science of Successful Learning",
      "type": "book",
      "url": "https://www.hup.harvard.edu/books/9780674729018",
      "authors": ["Peter C. Brown", "Henry L. Roediger III", "Mark A. McDaniel"],
      "publisher": "Harvard University Press",
      "published_date": "2014-01-01",
      "tags": ["learning-science", "memory", "retrieval-practice", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "The science of durable learning: retrieval practice, spaced repetition, interleaving, desirable difficulties. The evidence base for how humans actually remember things, written for a general audience by two leading memory researchers.",
      "personal_notes": null
    },
    {
      "slug": "how-people-learn-ii",
      "collection": "design-ai-learning",
      "title": "How People Learn II: Learners, Contexts, and Cultures",
      "type": "paper",
      "url": "https://nap.nationalacademies.org/catalog/24783/how-people-learn-ii-learners-contexts-and-cultures",
      "authors": ["National Academies of Sciences, Engineering, and Medicine"],
      "publisher": "National Academies Press",
      "published_date": "2018-01-01",
      "tags": ["learning-science", "consensus-report", "free", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "The consensus synthesis of the learning sciences — development, culture, motivation, memory, technology. The authoritative citation when you need one; free to read online.",
      "personal_notes": null
    },
    {
      "slug": "why-minimal-guidance-does-not-work",
      "collection": "design-ai-learning",
      "title": "Why Minimal Guidance During Instruction Does Not Work",
      "type": "paper",
      "url": "https://www.cogtech.usc.edu/publications/kirschner_Sweller_Clark.pdf",
      "authors": ["Paul A. Kirschner", "John Sweller", "Richard E. Clark"],
      "publisher": "Educational Psychologist",
      "published_date": "2006-01-01",
      "tags": ["learning-science", "cognitive-load", "direct-instruction", "classic-paper"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "Sharply argued case against pure discovery learning, grounded in working-memory limits. The central tension — guidance vs. exploration — is exactly what LLM tutoring reopens; grapple with this before designing any AI-mediated learning experience.",
      "personal_notes": null
    },
    {
      "slug": "science-of-learning-deans-for-impact",
      "collection": "design-ai-learning",
      "title": "The Science of Learning",
      "type": "paper",
      "url": "https://deansforimpact.org/resources/the-science-of-learning/",
      "authors": ["Deans for Impact"],
      "publisher": "Deans for Impact",
      "published_date": "2015-01-01",
      "tags": ["learning-science", "synthesis", "free"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "A remarkably short, clear synthesis of cognitive science for teacher educators: six learning principles, each grounded in the empirical literature. The cheat sheet to keep handy.",
      "personal_notes": null
    },
    {
      "slug": "memorable-teaching",
      "collection": "design-ai-learning",
      "title": "Memorable Teaching: Leveraging Memory to Build Deep and Durable Learning",
      "type": "book",
      "url": "https://pepsmccrea.com/memorable-teaching/",
      "authors": ["Peps Mccrea"],
      "publisher": "High Impact Teaching",
      "published_date": "2017-01-01",
      "tags": ["learning-science", "cognitive-load", "concise"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Concise primer (under 100 pages) on applying working-memory and long-term-memory research in the classroom. The fastest route into cognitive load theory.",
      "personal_notes": null
    },
    {
      "slug": "uncommon-sense-teaching",
      "collection": "design-ai-learning",
      "title": "Uncommon Sense Teaching",
      "type": "book",
      "url": "https://barbaraoakley.com/books/uncommon-sense-teaching/",
      "authors": ["Barbara Oakley", "Beth Rogowsky", "Terrence J. Sejnowski"],
      "publisher": "TarcherPerigee",
      "published_date": "2021-01-01",
      "tags": ["learning-science", "neuroscience", "practical"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "A neuroscientist, a teacher educator, and a computational biologist distill learning research into classroom-usable chapters on attention, memory, and diverse learners. A more recent synthesis; pairs well with Willingham.",
      "personal_notes": null
    },
    {
      "slug": "cognitive-load-theory",
      "collection": "design-ai-learning",
      "title": "Cognitive Load Theory",
      "type": "book",
      "url": "https://link.springer.com/book/10.1007/978-1-4419-8126-4",
      "authors": ["John Sweller", "Paul Ayres", "Slava Kalyuga"],
      "publisher": "Springer",
      "published_date": "2011-01-01",
      "tags": ["learning-science", "cognitive-load", "academic"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The canonical academic treatment of CLT by its originator. Dense but foundational — when anyone talks about 'chunking' and 'worked examples,' this is the source.",
      "personal_notes": null
    },
    {
      "slug": "embedded-formative-assessment",
      "collection": "design-ai-learning",
      "title": "Embedded Formative Assessment",
      "type": "book",
      "url": "https://us.corwin.com/books/embedded-formative-assess-2e-262099",
      "authors": ["Dylan Wiliam"],
      "publisher": "Solution Tree",
      "published_date": "2011-01-01",
      "tags": ["pedagogy", "assessment", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "The most influential modern treatment of formative assessment: five key strategies with practical classroom techniques for each. Formative feedback is arguably the most consequential teaching practice — and exactly where LLMs could meaningfully help or harm.",
      "personal_notes": null
    },
    {
      "slug": "creating-the-schools-our-children-need",
      "collection": "design-ai-learning",
      "title": "Creating the Schools Our Children Need",
      "type": "book",
      "url": "https://www.learningsciences.com/books/creating-the-schools-our-children-need/",
      "authors": ["Dylan Wiliam"],
      "publisher": "Learning Sciences International",
      "published_date": "2018-01-01",
      "tags": ["pedagogy", "policy", "systems"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Wiliam at the policy level: curriculum, instruction, and teacher professional development over tech silver bullets. A sober framing for any AI-in-schools conversation.",
      "personal_notes": null
    },
    {
      "slug": "teach-like-a-champion-3",
      "collection": "design-ai-learning",
      "title": "Teach Like a Champion 3.0",
      "type": "book",
      "url": "https://teachlikeachampion.org/books/teach-like-a-champion-3-0/",
      "authors": ["Doug Lemov"],
      "publisher": "Jossey-Bass",
      "published_date": "2021-01-01",
      "tags": ["pedagogy", "techniques", "practical"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Sixty-some concrete classroom techniques distilled from observing effective teachers. What the moves of skilled teaching actually look like — worth knowing before thinking about how to augment them.",
      "personal_notes": null
    },
    {
      "slug": "those-who-understand-shulman",
      "collection": "design-ai-learning",
      "title": "Those Who Understand: Knowledge Growth in Teaching",
      "type": "paper",
      "url": "https://www.jstor.org/stable/1175860",
      "authors": ["Lee S. Shulman"],
      "publisher": "Educational Researcher",
      "published_date": "1986-01-01",
      "tags": ["pedagogy", "pck", "classic-paper", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "The paper that introduced 'pedagogical content knowledge' — good teaching requires a distinct kind of knowledge that is neither just content nor just method. Essential framing for what teachers know that LLMs don't, and possibly can't.",
      "personal_notes": null
    },
    {
      "slug": "the-knowledge-gap",
      "collection": "design-ai-learning",
      "title": "The Knowledge Gap",
      "type": "book",
      "url": "https://nataliewexler.com/the-knowledge-gap/",
      "authors": ["Natalie Wexler"],
      "publisher": "Avery",
      "published_date": "2019-01-01",
      "tags": ["pedagogy", "reading", "knowledge-building"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Why American elementary reading instruction fails: the neglect of background knowledge. Large implications for AI-mediated learning — if knowledge-building lifts comprehension, chat-with-a-bot models may starve students of what they need.",
      "personal_notes": null
    },
    {
      "slug": "visible-learning",
      "collection": "design-ai-learning",
      "title": "Visible Learning",
      "type": "book",
      "url": "https://www.visiblelearningmetax.com/",
      "authors": ["John Hattie"],
      "publisher": "Routledge",
      "published_date": "2009-01-01",
      "tags": ["pedagogy", "meta-analysis", "reference", "contested"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Synthesis of 800+ meta-analyses of what influences student achievement, ranked by effect size. Methodology is contested, but the catalog is indispensable as a reference. Read critically.",
      "personal_notes": null
    },
    {
      "slug": "rosenshines-principles-in-action",
      "collection": "design-ai-learning",
      "title": "Rosenshine's Principles in Action",
      "type": "book",
      "url": "https://www.johncattbookshop.com/products/rosenshine-s-principles-in-action",
      "authors": ["Tom Sherrington"],
      "publisher": "John Catt",
      "published_date": "2019-01-01",
      "tags": ["pedagogy", "rosenshine", "direct-instruction", "concise"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Short, sharp walkthrough of Rosenshine's 10 principles of instruction, drawn from cognitive science and master-teacher research. The best pocket-sized summary of effective direct instruction.",
      "personal_notes": null
    },
    {
      "slug": "blooms-2-sigma-problem",
      "collection": "design-ai-learning",
      "title": "The 2 Sigma Problem",
      "type": "paper",
      "url": "https://web.mit.edu/5.95/readings/bloom-two-sigma.pdf",
      "authors": ["Benjamin S. Bloom"],
      "publisher": "Educational Researcher",
      "published_date": "1984-01-01",
      "tags": ["pedagogy", "tutoring", "classic-paper", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "One-to-one tutoring produces outcomes two standard deviations above conventional instruction; the challenge is finding scalable group methods that approach it. The founding ambition behind every AI-tutor pitch — read it so you know exactly what's being promised.",
      "personal_notes": null
    },
    {
      "slug": "the-gardener-and-the-carpenter",
      "collection": "design-ai-learning",
      "title": "The Gardener and the Carpenter",
      "type": "book",
      "url": "https://us.macmillan.com/books/9780374229702/thegardenerandthecarpenter",
      "authors": ["Alison Gopnik"],
      "publisher": "Farrar, Straus and Giroux",
      "published_date": "2016-01-01",
      "tags": ["child-development", "philosophy"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Development as gardening (creating an environment where children flourish), not carpentry (shaping a product). A needed counterweight to curriculum-as-delivery thinking; Gopnik is also sharp on what LLMs actually are.",
      "personal_notes": null
    },
    {
      "slug": "the-philosophical-baby",
      "collection": "design-ai-learning",
      "title": "The Philosophical Baby",
      "type": "book",
      "url": "https://alisongopnik.com/philosophicalbaby.htm",
      "authors": ["Alison Gopnik"],
      "publisher": "Farrar, Straus and Giroux",
      "published_date": "2009-01-01",
      "tags": ["child-development", "cognition"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "What babies and young children reveal about learning, imagination, and consciousness. Why children are such remarkable learners — and why statistical pattern-matching is only a slice of the story.",
      "personal_notes": null
    },
    {
      "slug": "mindstorms",
      "collection": "design-ai-learning",
      "title": "Mindstorms: Children, Computers, and Powerful Ideas",
      "type": "book",
      "url": "https://en.wikipedia.org/wiki/Mindstorms_(book)",
      "authors": ["Seymour Papert"],
      "publisher": "Basic Books",
      "published_date": "1980-01-01",
      "tags": ["child-development", "constructionism", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "Papert's manifesto on children as builders and debuggers of ideas — the intellectual foundation of Logo, Scratch, and constructionist education. Saw the questions LLMs force us to re-ask (agency, tools, machines doing things for children vs. with them) forty years early.",
      "personal_notes": null
    },
    {
      "slug": "lifelong-kindergarten",
      "collection": "design-ai-learning",
      "title": "Lifelong Kindergarten: Cultivating Creativity through Projects, Passion, Peers, and Play",
      "type": "book",
      "url": "https://mitpress.mit.edu/9780262536134/lifelong-kindergarten/",
      "authors": ["Mitchel Resnick"],
      "publisher": "MIT Press",
      "published_date": "2017-01-01",
      "tags": ["child-development", "constructionism", "creativity"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The head of the MIT Media Lab group that created Scratch argues the kindergarten model — projects, passion, peers, play — should extend throughout life. A direct descendant of Papert and a strong alternative vision to 'personalized instruction via chatbot.'",
      "personal_notes": null
    },
    {
      "slug": "mind-in-society",
      "collection": "design-ai-learning",
      "title": "Mind in Society: The Development of Higher Psychological Processes",
      "type": "book",
      "url": "https://www.hup.harvard.edu/books/9780674576292",
      "authors": ["Lev S. Vygotsky"],
      "publisher": "Harvard University Press",
      "published_date": "1978-01-01",
      "tags": ["child-development", "social-learning", "zpd", "foundational"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Zone of proximal development, scaffolding, the social origins of higher mental function. 'Scaffolding' is the word everyone uses for what good tutors do — this is where it comes from. Dense but worth it.",
      "personal_notes": null
    },
    {
      "slug": "the-process-of-education",
      "collection": "design-ai-learning",
      "title": "The Process of Education",
      "type": "book",
      "url": "https://www.hup.harvard.edu/books/9780674710016",
      "authors": ["Jerome Bruner"],
      "publisher": "Harvard University Press",
      "published_date": "1960-01-01",
      "tags": ["child-development", "curriculum", "spiral-curriculum"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Short, foundational: any subject can be taught honestly to a child at any age — the origin of the spiral curriculum. A useful corrective to narrow developmentalism and 'wait until they're ready' thinking.",
      "personal_notes": null
    },
    {
      "slug": "teachers-and-machines",
      "collection": "design-ai-learning",
      "title": "Teachers and Machines: The Classroom Use of Technology Since 1920",
      "type": "book",
      "url": "https://larrycuban.wordpress.com/",
      "authors": ["Larry Cuban"],
      "publisher": "Teachers College Press",
      "published_date": "1986-01-01",
      "tags": ["edtech-history", "skeptic", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "The historical anchor: film, radio, television, computers — each promised to revolutionize schooling, each largely didn't. You cannot think well about AI in schools without this baseline.",
      "personal_notes": null
    },
    {
      "slug": "oversold-and-underused",
      "collection": "design-ai-learning",
      "title": "Oversold and Underused: Computers in the Classroom",
      "type": "book",
      "url": "https://www.hup.harvard.edu/books/9780674011090",
      "authors": ["Larry Cuban"],
      "publisher": "Harvard University Press",
      "published_date": "2001-01-01",
      "tags": ["edtech-history", "skeptic"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The 1990s personal-computer wave in classrooms: a persistent gap between tech investment and pedagogical change. The patterns recur exactly in the AI era; forewarned is forearmed.",
      "personal_notes": null
    },
    {
      "slug": "tinkering-toward-utopia",
      "collection": "design-ai-learning",
      "title": "Tinkering Toward Utopia: A Century of Public School Reform",
      "type": "book",
      "url": "https://www.hup.harvard.edu/books/9780674892835",
      "authors": ["David Tyack", "Larry Cuban"],
      "publisher": "Harvard University Press",
      "published_date": "1995-01-01",
      "tags": ["edtech-history", "reform", "grammar-of-schooling"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Why waves of reform get absorbed rather than transform schooling — the 'grammar of schooling.' Crucial for understanding what will and won't change when AI meets real classrooms, districts, and unions.",
      "personal_notes": null
    },
    {
      "slug": "failure-to-disrupt",
      "collection": "design-ai-learning",
      "title": "Failure to Disrupt: Why Technology Alone Can't Transform Education",
      "type": "book",
      "url": "https://tsl.mit.edu/books/failure-to-disrupt/",
      "authors": ["Justin Reich"],
      "publisher": "Harvard University Press",
      "published_date": "2020-01-01",
      "tags": ["edtech-history", "learning-at-scale", "skeptic", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "MIT Teaching Systems Lab director surveys MOOCs, adaptive tutors, and learning at scale — and the intractable dilemmas that keep stopping them (the curse of the familiar, the Matthew effect, the trap of routine assessment). The single best book on what to expect from AI in classrooms.",
      "personal_notes": null
    },
    {
      "slug": "iterate",
      "collection": "design-ai-learning",
      "title": "Iterate: The Secret to Innovation in Schools",
      "type": "book",
      "url": "https://tsl.mit.edu/books/iterate/",
      "authors": ["Justin Reich"],
      "publisher": "Jossey-Bass",
      "published_date": "2023-01-01",
      "tags": ["edtech-history", "improvement", "practice"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Reich's constructive sequel: schools get better through cycles of experimentation and collective learning, not disruption. Pair with Failure to Disrupt — the first shows what doesn't work; this shows what might.",
      "personal_notes": null
    },
    {
      "slug": "teaching-machines",
      "collection": "design-ai-learning",
      "title": "Teaching Machines: The History of Personalized Learning",
      "type": "book",
      "url": "https://mitpress.mit.edu/9780262045698/teaching-machines/",
      "authors": ["Audrey Watters"],
      "publisher": "MIT Press",
      "published_date": "2021-01-01",
      "tags": ["edtech-history", "behaviorism", "skeptic"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "A cultural history of 'teaching machines' from Pressey and Skinner through modern software: personalized-learning dreams are a century old. Arms you against the 'this time it's different' AI pitch.",
      "personal_notes": null
    },
    {
      "slug": "co-intelligence",
      "collection": "design-ai-learning",
      "title": "Co-Intelligence: Living and Working with AI",
      "type": "book",
      "url": "https://www.penguinrandomhouse.com/books/741805/co-intelligence-by-ethan-mollick/",
      "authors": ["Ethan Mollick"],
      "publisher": "Portfolio",
      "published_date": "2024-01-01",
      "tags": ["ai-in-education", "optimist", "practical"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "Wharton professor's practical guide to working with LLMs — AI as co-worker, co-teacher, coach — with a substantive education chapter. The most useful single book for thinking pragmatically about AI in learning; pair with skeptical voices.",
      "personal_notes": null
    },
    {
      "slug": "brave-new-words",
      "collection": "design-ai-learning",
      "title": "Brave New Words: How AI Will Revolutionize Education",
      "type": "book",
      "url": "https://www.penguinrandomhouse.com/books/744469/brave-new-words-by-salman-khan/",
      "authors": ["Salman Khan"],
      "publisher": "Viking",
      "published_date": "2024-01-01",
      "tags": ["ai-in-education", "optimist", "tutoring"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The Khan Academy founder's vision for AI tutoring, featuring Khanmigo. Optimistic and concrete; read even if skeptical — this is the vision driving much of the industry investment.",
      "personal_notes": null
    },
    {
      "slug": "machine-learning-and-human-intelligence",
      "collection": "design-ai-learning",
      "title": "Machine Learning and Human Intelligence: The Future of Education for the 21st Century",
      "type": "book",
      "url": "https://www.ucl-ioe-press.com/books/education-policy/machine-learning-and-human-intelligence/",
      "authors": ["Rose Luckin"],
      "publisher": "UCL IOE Press",
      "published_date": "2018-01-01",
      "tags": ["ai-in-education", "academic", "aied"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "UCL professor and long-time AIED researcher on how AI can complement human intelligence in learning. Predates the LLM wave but intellectually serious — a European academic perspective that's neither hype nor doom.",
      "personal_notes": null
    },
    {
      "slug": "artificial-intelligence-in-education-holmes",
      "collection": "design-ai-learning",
      "title": "Artificial Intelligence in Education: Promises and Implications for Teaching and Learning",
      "type": "book",
      "url": "https://curriculumredesign.org/artificial-intelligence-in-education/",
      "authors": ["Wayne Holmes", "Maya Bialik", "Charles Fadel"],
      "publisher": "Center for Curriculum Redesign",
      "published_date": "2019-01-01",
      "tags": ["ai-in-education", "survey", "policy"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Fair-minded, well-sourced survey of AI in education: intelligent tutors, learning analytics, policy implications. The landscape rather than a single argument.",
      "personal_notes": null
    },
    {
      "slug": "critical-ai-in-k12-classrooms",
      "collection": "design-ai-learning",
      "title": "Critical AI in K-12 Classrooms",
      "type": "book",
      "url": "https://hep.gse.harvard.edu/9798895570180/critical-ai-in-k-12-classrooms/",
      "authors": ["Stephanie Smith Budhai", "Marie K. Heath"],
      "publisher": "Harvard Education Press",
      "published_date": "2024-01-01",
      "tags": ["ai-in-education", "skeptic", "equity"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Examines bias, equity, and classroom pedagogy implications of GenAI and LLMs through a critical lens. The who-benefits, who-gets-harmed conversation needs this kind of close reading.",
      "personal_notes": null
    },
    {
      "slug": "ai-snake-oil-book",
      "collection": "design-ai-learning",
      "title": "AI Snake Oil: What Artificial Intelligence Can Do, What It Can't, and How to Tell the Difference",
      "type": "book",
      "url": "https://www.aisnakeoil.com/p/the-book",
      "authors": ["Arvind Narayanan", "Sayash Kapoor"],
      "publisher": "Princeton University Press",
      "published_date": "2024-01-01",
      "tags": ["ai-in-education", "skeptic", "technical"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Princeton computer scientists separate what AI can do from what vendors claim. Not education-specific but essential context — sharpens your ability to read ed-tech marketing critically.",
      "personal_notes": null
    },
    {
      "slug": "one-useful-thing",
      "collection": "design-ai-learning",
      "title": "One Useful Thing",
      "type": "website",
      "url": "https://www.oneusefulthing.org/",
      "authors": ["Ethan Mollick"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["ai-in-education", "optimist", "ongoing", "practical"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "The most-read Substack on practical uses of LLMs: hands-on experiments, prompt examples, teaching reflections. The pragmatic pulse of where LLMs can actually help. Read weekly.",
      "personal_notes": null
    },
    {
      "slug": "cognitive-resonance",
      "collection": "design-ai-learning",
      "title": "Cognitive Resonance",
      "type": "website",
      "url": "https://buildcognitiveresonance.substack.com/",
      "authors": ["Benjamin Riley"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["ai-in-education", "skeptic", "ongoing", "cognitive-science"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "Founder of Deans for Impact writes a cognitive-science-grounded critique of AI hype in education. The essential counterweight to Mollick — reading both makes you smart about the actual tradeoffs.",
      "personal_notes": null
    },
    {
      "slug": "willingham-science-and-education-blog",
      "collection": "design-ai-learning",
      "title": "Daniel Willingham — Science & Education Blog",
      "type": "website",
      "url": "https://www.danielwillingham.com/daniel-willingham-science-and-education-blog.html",
      "authors": ["Daniel T. Willingham"],
      "publisher": "danielwillingham.com",
      "published_date": null,
      "tags": ["learning-science", "ongoing", "translation"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The author of Why Don't Students Like School? continues translating cognitive science for practitioners. When a new learning-science study drops, wait for Willingham's take.",
      "personal_notes": null
    },
    {
      "slug": "mathworlds",
      "collection": "design-ai-learning",
      "title": "Mathworlds (dy/dan)",
      "type": "website",
      "url": "https://danmeyer.substack.com/",
      "authors": ["Dan Meyer"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["pedagogy", "math", "skeptic", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Math educator and researcher, influential on problem-based learning and critical of edtech overclaims. Incisive on what actually makes learning stick in math classrooms, including with AI.",
      "personal_notes": null
    },
    {
      "slug": "filling-the-pail",
      "collection": "design-ai-learning",
      "title": "Filling the Pail",
      "type": "website",
      "url": "https://fillingthepail.substack.com/",
      "authors": ["Greg Ashman"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["learning-science", "cognitive-load", "skeptic", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Australian teacher-researcher on explicit instruction, cognitive load, and rigorous ed research. Will call out weak research and wishful thinking — including from progressive and edtech camps.",
      "personal_notes": null
    },
    {
      "slug": "teacherhead",
      "collection": "design-ai-learning",
      "title": "teacherhead",
      "type": "website",
      "url": "https://teacherhead.com/",
      "authors": ["Tom Sherrington"],
      "publisher": "teacherhead.com",
      "published_date": null,
      "tags": ["pedagogy", "practice", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Former UK headteacher, author of Rosenshine's Principles in Action, prolific on pedagogy, curriculum, and classroom craft. Consistently good on the gap between research and classroom reality.",
      "personal_notes": null
    },
    {
      "slug": "second-breakfast",
      "collection": "design-ai-learning",
      "title": "Second Breakfast (and the Hack Education archive)",
      "type": "website",
      "url": "https://2ndbreakfast.audreywatters.com/",
      "authors": ["Audrey Watters"],
      "publisher": "audreywatters.com",
      "published_date": null,
      "tags": ["edtech-history", "skeptic", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Long-time ed-tech historian and critic; the Hack Education archive (2010–2022) is a reference library of ed-tech skepticism. The memory of edtech — essential for not repeating the last hype cycle.",
      "personal_notes": null
    },
    {
      "slug": "minding-the-gap",
      "collection": "design-ai-learning",
      "title": "Minding the Gap",
      "type": "website",
      "url": "https://nataliewexler.substack.com/",
      "authors": ["Natalie Wexler"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["pedagogy", "writing", "literacy", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The author of The Knowledge Gap on literacy, writing instruction, curriculum, and increasingly AI. Especially good on writing pedagogy — the skill most directly affected by LLMs.",
      "personal_notes": null
    },
    {
      "slug": "the-answer-pondiscio",
      "collection": "design-ai-learning",
      "title": "The Answer",
      "type": "website",
      "url": "https://robertpondiscio.substack.com/",
      "authors": ["Robert Pondiscio"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["policy", "knowledge-building", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "AEI fellow and former NYC teacher on curriculum, knowledge, and school reform from a conservative-reformist lens. Strong on the knowledge-building argument and policy realities.",
      "personal_notes": null
    },
    {
      "slug": "larry-cuban-blog",
      "collection": "design-ai-learning",
      "title": "Larry Cuban on School Reform and Classroom Practice",
      "type": "website",
      "url": "https://larrycuban.wordpress.com/",
      "authors": ["Larry Cuban"],
      "publisher": "WordPress",
      "published_date": null,
      "tags": ["edtech-history", "skeptic", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The historian of Teachers and Machines keeps blogging — classroom tech use, reform cycles, and now AI. A living connection to a century of ed-tech history.",
      "personal_notes": null
    },
    {
      "slug": "ai-snake-oil-newsletter",
      "collection": "design-ai-learning",
      "title": "AI Snake Oil (newsletter)",
      "type": "website",
      "url": "https://www.aisnakeoil.com/",
      "authors": ["Arvind Narayanan", "Sayash Kapoor"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["ai-in-education", "skeptic", "technical", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Sober, technically literate critique of AI claims across sectors including education. Helps you separate real LLM capabilities from marketing and evaluate vendor claims.",
      "personal_notes": null
    },
    {
      "slug": "the-biblioracle-recommends",
      "collection": "design-ai-learning",
      "title": "The Biblioracle Recommends",
      "type": "website",
      "url": "https://biblioracle.substack.com/",
      "authors": ["John Warner"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["writing", "pedagogy", "skeptic", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Writer and writing teacher; author of More Than Words: How to Think About Writing in the Age of AI. Specifically good on the 'should students still learn to write' question.",
      "personal_notes": null
    },
    {
      "slug": "larry-ferlazzo-websites-of-the-day",
      "collection": "design-ai-learning",
      "title": "Larry Ferlazzo's Websites of the Day",
      "type": "website",
      "url": "https://larryferlazzo.edublogs.org/",
      "authors": ["Larry Ferlazzo"],
      "publisher": "Edublogs",
      "published_date": null,
      "tags": ["practice", "aggregation", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Prolific Sacramento teacher-blogger aggregating ESL, classroom practice, and education news, now covering AI regularly. Useful for staying current on practitioner conversations.",
      "personal_notes": null
    },
    {
      "slug": "the-homework-apocalypse",
      "collection": "design-ai-learning",
      "title": "The Homework Apocalypse",
      "type": "article",
      "url": "https://www.oneusefulthing.org/p/the-homework-apocalypse",
      "authors": ["Ethan Mollick"],
      "publisher": "One Useful Thing (Substack)",
      "published_date": "2023-07-01",
      "tags": ["ai-in-education", "assessment", "writing", "optimist"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Most take-home assignments — essays, problem sets, reading summaries — can now be completed by free AI at passing quality, collapsing their assessment value. Sketches three responses: AI-proof assessment, AI-integrated assignments, and rethinking what practice is for.",
      "personal_notes": null
    },
    {
      "slug": "khan-ted-how-ai-could-save-education",
      "collection": "design-ai-learning",
      "title": "How AI Could Save (Not Destroy) Education",
      "type": "video",
      "url": "https://www.ted.com/talks/sal_khan_how_ai_could_save_not_destroy_education",
      "authors": ["Salman Khan"],
      "publisher": "TED",
      "published_date": "2023-05-01",
      "tags": ["ai-in-education", "optimist", "tutoring"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The Khanmigo vision in 15 minutes: AI as a personal tutor for every student and an assistant for every teacher. Watch as the strongest, most concise version of the optimist case.",
      "personal_notes": null
    },
    {
      "slug": "teachlab-podcast",
      "collection": "design-ai-learning",
      "title": "TeachLab",
      "type": "podcast",
      "url": "https://tsl.mit.edu/teachlab_podcast/",
      "authors": ["Justin Reich"],
      "publisher": "MIT Teaching Systems Lab",
      "published_date": null,
      "tags": ["pedagogy", "edtech-history", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Conversations on teaching, learning, and technology from the MIT Teaching Systems Lab — Reich interviewing researchers and practitioners. Good companion listening to Failure to Disrupt.",
      "personal_notes": null
    }
  ]
}

$seed$::jsonb as data
), collection_rows as (
  select collection
  from seed, jsonb_array_elements(data->'collections') as collection
)
insert into public.collections (name, slug, description, is_research)
select
  collection->>'name',
  collection->>'slug',
  collection->>'description',
  coalesce((collection->>'is_research')::boolean, true)
from collection_rows
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  is_research = excluded.is_research;

with seed as (
  select $seed$
{
  "_meta": {
    "description": "Seed dataset for Readable. Generated from the 'Learning, Teaching & AI' curated reading list (April 2026 planning conversation).",
    "notes": "cliff_notes here are brief curation seeds written during list compilation — suitable placeholders, intentionally short. For fuller notes, re-run resources through the ingestion pipeline after launch (drafts via INGEST_MODEL, then human review). published_date uses YYYY-01-01 when only the year is known; null for ongoing publications. All statuses default to 'unread' — the owner marks real reading history after import.",
    "schema_version": 1
  },
  "collections": [
    {
      "name": "Design × AI × Learning",
      "slug": "design-ai-learning",
      "description": "Research and expert opinion at the intersection of design, AI/LLMs, and K-12 teaching & learning. Foundations first: learning science, pedagogy, child development, and edtech history beneath the AI-era debate.",
      "is_research": true
    }
  ],
  "resources": [
    {
      "slug": "why-dont-students-like-school",
      "collection": "design-ai-learning",
      "title": "Why Don't Students Like School?",
      "type": "book",
      "url": "https://www.danielwillingham.com/why-dont-students-like-school.html",
      "authors": ["Daniel T. Willingham"],
      "publisher": "Jossey-Bass",
      "published_date": "2021-01-01",
      "tags": ["learning-science", "cognitive-science", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "A cognitive scientist explains nine principles of how the mind works and what they mean for classroom practice. The single most efficient way to get a grounded model of student cognition; nearly every good teacher book cites it.",
      "personal_notes": null
    },
    {
      "slug": "make-it-stick",
      "collection": "design-ai-learning",
      "title": "Make It Stick: The Science of Successful Learning",
      "type": "book",
      "url": "https://www.hup.harvard.edu/books/9780674729018",
      "authors": ["Peter C. Brown", "Henry L. Roediger III", "Mark A. McDaniel"],
      "publisher": "Harvard University Press",
      "published_date": "2014-01-01",
      "tags": ["learning-science", "memory", "retrieval-practice", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "The science of durable learning: retrieval practice, spaced repetition, interleaving, desirable difficulties. The evidence base for how humans actually remember things, written for a general audience by two leading memory researchers.",
      "personal_notes": null
    },
    {
      "slug": "how-people-learn-ii",
      "collection": "design-ai-learning",
      "title": "How People Learn II: Learners, Contexts, and Cultures",
      "type": "paper",
      "url": "https://nap.nationalacademies.org/catalog/24783/how-people-learn-ii-learners-contexts-and-cultures",
      "authors": ["National Academies of Sciences, Engineering, and Medicine"],
      "publisher": "National Academies Press",
      "published_date": "2018-01-01",
      "tags": ["learning-science", "consensus-report", "free", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "The consensus synthesis of the learning sciences — development, culture, motivation, memory, technology. The authoritative citation when you need one; free to read online.",
      "personal_notes": null
    },
    {
      "slug": "why-minimal-guidance-does-not-work",
      "collection": "design-ai-learning",
      "title": "Why Minimal Guidance During Instruction Does Not Work",
      "type": "paper",
      "url": "https://www.cogtech.usc.edu/publications/kirschner_Sweller_Clark.pdf",
      "authors": ["Paul A. Kirschner", "John Sweller", "Richard E. Clark"],
      "publisher": "Educational Psychologist",
      "published_date": "2006-01-01",
      "tags": ["learning-science", "cognitive-load", "direct-instruction", "classic-paper"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "Sharply argued case against pure discovery learning, grounded in working-memory limits. The central tension — guidance vs. exploration — is exactly what LLM tutoring reopens; grapple with this before designing any AI-mediated learning experience.",
      "personal_notes": null
    },
    {
      "slug": "science-of-learning-deans-for-impact",
      "collection": "design-ai-learning",
      "title": "The Science of Learning",
      "type": "paper",
      "url": "https://deansforimpact.org/resources/the-science-of-learning/",
      "authors": ["Deans for Impact"],
      "publisher": "Deans for Impact",
      "published_date": "2015-01-01",
      "tags": ["learning-science", "synthesis", "free"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "A remarkably short, clear synthesis of cognitive science for teacher educators: six learning principles, each grounded in the empirical literature. The cheat sheet to keep handy.",
      "personal_notes": null
    },
    {
      "slug": "memorable-teaching",
      "collection": "design-ai-learning",
      "title": "Memorable Teaching: Leveraging Memory to Build Deep and Durable Learning",
      "type": "book",
      "url": "https://pepsmccrea.com/memorable-teaching/",
      "authors": ["Peps Mccrea"],
      "publisher": "High Impact Teaching",
      "published_date": "2017-01-01",
      "tags": ["learning-science", "cognitive-load", "concise"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Concise primer (under 100 pages) on applying working-memory and long-term-memory research in the classroom. The fastest route into cognitive load theory.",
      "personal_notes": null
    },
    {
      "slug": "uncommon-sense-teaching",
      "collection": "design-ai-learning",
      "title": "Uncommon Sense Teaching",
      "type": "book",
      "url": "https://barbaraoakley.com/books/uncommon-sense-teaching/",
      "authors": ["Barbara Oakley", "Beth Rogowsky", "Terrence J. Sejnowski"],
      "publisher": "TarcherPerigee",
      "published_date": "2021-01-01",
      "tags": ["learning-science", "neuroscience", "practical"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "A neuroscientist, a teacher educator, and a computational biologist distill learning research into classroom-usable chapters on attention, memory, and diverse learners. A more recent synthesis; pairs well with Willingham.",
      "personal_notes": null
    },
    {
      "slug": "cognitive-load-theory",
      "collection": "design-ai-learning",
      "title": "Cognitive Load Theory",
      "type": "book",
      "url": "https://link.springer.com/book/10.1007/978-1-4419-8126-4",
      "authors": ["John Sweller", "Paul Ayres", "Slava Kalyuga"],
      "publisher": "Springer",
      "published_date": "2011-01-01",
      "tags": ["learning-science", "cognitive-load", "academic"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The canonical academic treatment of CLT by its originator. Dense but foundational — when anyone talks about 'chunking' and 'worked examples,' this is the source.",
      "personal_notes": null
    },
    {
      "slug": "embedded-formative-assessment",
      "collection": "design-ai-learning",
      "title": "Embedded Formative Assessment",
      "type": "book",
      "url": "https://us.corwin.com/books/embedded-formative-assess-2e-262099",
      "authors": ["Dylan Wiliam"],
      "publisher": "Solution Tree",
      "published_date": "2011-01-01",
      "tags": ["pedagogy", "assessment", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "The most influential modern treatment of formative assessment: five key strategies with practical classroom techniques for each. Formative feedback is arguably the most consequential teaching practice — and exactly where LLMs could meaningfully help or harm.",
      "personal_notes": null
    },
    {
      "slug": "creating-the-schools-our-children-need",
      "collection": "design-ai-learning",
      "title": "Creating the Schools Our Children Need",
      "type": "book",
      "url": "https://www.learningsciences.com/books/creating-the-schools-our-children-need/",
      "authors": ["Dylan Wiliam"],
      "publisher": "Learning Sciences International",
      "published_date": "2018-01-01",
      "tags": ["pedagogy", "policy", "systems"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Wiliam at the policy level: curriculum, instruction, and teacher professional development over tech silver bullets. A sober framing for any AI-in-schools conversation.",
      "personal_notes": null
    },
    {
      "slug": "teach-like-a-champion-3",
      "collection": "design-ai-learning",
      "title": "Teach Like a Champion 3.0",
      "type": "book",
      "url": "https://teachlikeachampion.org/books/teach-like-a-champion-3-0/",
      "authors": ["Doug Lemov"],
      "publisher": "Jossey-Bass",
      "published_date": "2021-01-01",
      "tags": ["pedagogy", "techniques", "practical"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Sixty-some concrete classroom techniques distilled from observing effective teachers. What the moves of skilled teaching actually look like — worth knowing before thinking about how to augment them.",
      "personal_notes": null
    },
    {
      "slug": "those-who-understand-shulman",
      "collection": "design-ai-learning",
      "title": "Those Who Understand: Knowledge Growth in Teaching",
      "type": "paper",
      "url": "https://www.jstor.org/stable/1175860",
      "authors": ["Lee S. Shulman"],
      "publisher": "Educational Researcher",
      "published_date": "1986-01-01",
      "tags": ["pedagogy", "pck", "classic-paper", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "The paper that introduced 'pedagogical content knowledge' — good teaching requires a distinct kind of knowledge that is neither just content nor just method. Essential framing for what teachers know that LLMs don't, and possibly can't.",
      "personal_notes": null
    },
    {
      "slug": "the-knowledge-gap",
      "collection": "design-ai-learning",
      "title": "The Knowledge Gap",
      "type": "book",
      "url": "https://nataliewexler.com/the-knowledge-gap/",
      "authors": ["Natalie Wexler"],
      "publisher": "Avery",
      "published_date": "2019-01-01",
      "tags": ["pedagogy", "reading", "knowledge-building"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Why American elementary reading instruction fails: the neglect of background knowledge. Large implications for AI-mediated learning — if knowledge-building lifts comprehension, chat-with-a-bot models may starve students of what they need.",
      "personal_notes": null
    },
    {
      "slug": "visible-learning",
      "collection": "design-ai-learning",
      "title": "Visible Learning",
      "type": "book",
      "url": "https://www.visiblelearningmetax.com/",
      "authors": ["John Hattie"],
      "publisher": "Routledge",
      "published_date": "2009-01-01",
      "tags": ["pedagogy", "meta-analysis", "reference", "contested"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Synthesis of 800+ meta-analyses of what influences student achievement, ranked by effect size. Methodology is contested, but the catalog is indispensable as a reference. Read critically.",
      "personal_notes": null
    },
    {
      "slug": "rosenshines-principles-in-action",
      "collection": "design-ai-learning",
      "title": "Rosenshine's Principles in Action",
      "type": "book",
      "url": "https://www.johncattbookshop.com/products/rosenshine-s-principles-in-action",
      "authors": ["Tom Sherrington"],
      "publisher": "John Catt",
      "published_date": "2019-01-01",
      "tags": ["pedagogy", "rosenshine", "direct-instruction", "concise"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Short, sharp walkthrough of Rosenshine's 10 principles of instruction, drawn from cognitive science and master-teacher research. The best pocket-sized summary of effective direct instruction.",
      "personal_notes": null
    },
    {
      "slug": "blooms-2-sigma-problem",
      "collection": "design-ai-learning",
      "title": "The 2 Sigma Problem",
      "type": "paper",
      "url": "https://web.mit.edu/5.95/readings/bloom-two-sigma.pdf",
      "authors": ["Benjamin S. Bloom"],
      "publisher": "Educational Researcher",
      "published_date": "1984-01-01",
      "tags": ["pedagogy", "tutoring", "classic-paper", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "One-to-one tutoring produces outcomes two standard deviations above conventional instruction; the challenge is finding scalable group methods that approach it. The founding ambition behind every AI-tutor pitch — read it so you know exactly what's being promised.",
      "personal_notes": null
    },
    {
      "slug": "the-gardener-and-the-carpenter",
      "collection": "design-ai-learning",
      "title": "The Gardener and the Carpenter",
      "type": "book",
      "url": "https://us.macmillan.com/books/9780374229702/thegardenerandthecarpenter",
      "authors": ["Alison Gopnik"],
      "publisher": "Farrar, Straus and Giroux",
      "published_date": "2016-01-01",
      "tags": ["child-development", "philosophy"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Development as gardening (creating an environment where children flourish), not carpentry (shaping a product). A needed counterweight to curriculum-as-delivery thinking; Gopnik is also sharp on what LLMs actually are.",
      "personal_notes": null
    },
    {
      "slug": "the-philosophical-baby",
      "collection": "design-ai-learning",
      "title": "The Philosophical Baby",
      "type": "book",
      "url": "https://alisongopnik.com/philosophicalbaby.htm",
      "authors": ["Alison Gopnik"],
      "publisher": "Farrar, Straus and Giroux",
      "published_date": "2009-01-01",
      "tags": ["child-development", "cognition"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "What babies and young children reveal about learning, imagination, and consciousness. Why children are such remarkable learners — and why statistical pattern-matching is only a slice of the story.",
      "personal_notes": null
    },
    {
      "slug": "mindstorms",
      "collection": "design-ai-learning",
      "title": "Mindstorms: Children, Computers, and Powerful Ideas",
      "type": "book",
      "url": "https://en.wikipedia.org/wiki/Mindstorms_(book)",
      "authors": ["Seymour Papert"],
      "publisher": "Basic Books",
      "published_date": "1980-01-01",
      "tags": ["child-development", "constructionism", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "Papert's manifesto on children as builders and debuggers of ideas — the intellectual foundation of Logo, Scratch, and constructionist education. Saw the questions LLMs force us to re-ask (agency, tools, machines doing things for children vs. with them) forty years early.",
      "personal_notes": null
    },
    {
      "slug": "lifelong-kindergarten",
      "collection": "design-ai-learning",
      "title": "Lifelong Kindergarten: Cultivating Creativity through Projects, Passion, Peers, and Play",
      "type": "book",
      "url": "https://mitpress.mit.edu/9780262536134/lifelong-kindergarten/",
      "authors": ["Mitchel Resnick"],
      "publisher": "MIT Press",
      "published_date": "2017-01-01",
      "tags": ["child-development", "constructionism", "creativity"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The head of the MIT Media Lab group that created Scratch argues the kindergarten model — projects, passion, peers, play — should extend throughout life. A direct descendant of Papert and a strong alternative vision to 'personalized instruction via chatbot.'",
      "personal_notes": null
    },
    {
      "slug": "mind-in-society",
      "collection": "design-ai-learning",
      "title": "Mind in Society: The Development of Higher Psychological Processes",
      "type": "book",
      "url": "https://www.hup.harvard.edu/books/9780674576292",
      "authors": ["Lev S. Vygotsky"],
      "publisher": "Harvard University Press",
      "published_date": "1978-01-01",
      "tags": ["child-development", "social-learning", "zpd", "foundational"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Zone of proximal development, scaffolding, the social origins of higher mental function. 'Scaffolding' is the word everyone uses for what good tutors do — this is where it comes from. Dense but worth it.",
      "personal_notes": null
    },
    {
      "slug": "the-process-of-education",
      "collection": "design-ai-learning",
      "title": "The Process of Education",
      "type": "book",
      "url": "https://www.hup.harvard.edu/books/9780674710016",
      "authors": ["Jerome Bruner"],
      "publisher": "Harvard University Press",
      "published_date": "1960-01-01",
      "tags": ["child-development", "curriculum", "spiral-curriculum"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Short, foundational: any subject can be taught honestly to a child at any age — the origin of the spiral curriculum. A useful corrective to narrow developmentalism and 'wait until they're ready' thinking.",
      "personal_notes": null
    },
    {
      "slug": "teachers-and-machines",
      "collection": "design-ai-learning",
      "title": "Teachers and Machines: The Classroom Use of Technology Since 1920",
      "type": "book",
      "url": "https://larrycuban.wordpress.com/",
      "authors": ["Larry Cuban"],
      "publisher": "Teachers College Press",
      "published_date": "1986-01-01",
      "tags": ["edtech-history", "skeptic", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "The historical anchor: film, radio, television, computers — each promised to revolutionize schooling, each largely didn't. You cannot think well about AI in schools without this baseline.",
      "personal_notes": null
    },
    {
      "slug": "oversold-and-underused",
      "collection": "design-ai-learning",
      "title": "Oversold and Underused: Computers in the Classroom",
      "type": "book",
      "url": "https://www.hup.harvard.edu/books/9780674011090",
      "authors": ["Larry Cuban"],
      "publisher": "Harvard University Press",
      "published_date": "2001-01-01",
      "tags": ["edtech-history", "skeptic"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The 1990s personal-computer wave in classrooms: a persistent gap between tech investment and pedagogical change. The patterns recur exactly in the AI era; forewarned is forearmed.",
      "personal_notes": null
    },
    {
      "slug": "tinkering-toward-utopia",
      "collection": "design-ai-learning",
      "title": "Tinkering Toward Utopia: A Century of Public School Reform",
      "type": "book",
      "url": "https://www.hup.harvard.edu/books/9780674892835",
      "authors": ["David Tyack", "Larry Cuban"],
      "publisher": "Harvard University Press",
      "published_date": "1995-01-01",
      "tags": ["edtech-history", "reform", "grammar-of-schooling"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Why waves of reform get absorbed rather than transform schooling — the 'grammar of schooling.' Crucial for understanding what will and won't change when AI meets real classrooms, districts, and unions.",
      "personal_notes": null
    },
    {
      "slug": "failure-to-disrupt",
      "collection": "design-ai-learning",
      "title": "Failure to Disrupt: Why Technology Alone Can't Transform Education",
      "type": "book",
      "url": "https://tsl.mit.edu/books/failure-to-disrupt/",
      "authors": ["Justin Reich"],
      "publisher": "Harvard University Press",
      "published_date": "2020-01-01",
      "tags": ["edtech-history", "learning-at-scale", "skeptic", "foundational"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "MIT Teaching Systems Lab director surveys MOOCs, adaptive tutors, and learning at scale — and the intractable dilemmas that keep stopping them (the curse of the familiar, the Matthew effect, the trap of routine assessment). The single best book on what to expect from AI in classrooms.",
      "personal_notes": null
    },
    {
      "slug": "iterate",
      "collection": "design-ai-learning",
      "title": "Iterate: The Secret to Innovation in Schools",
      "type": "book",
      "url": "https://tsl.mit.edu/books/iterate/",
      "authors": ["Justin Reich"],
      "publisher": "Jossey-Bass",
      "published_date": "2023-01-01",
      "tags": ["edtech-history", "improvement", "practice"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Reich's constructive sequel: schools get better through cycles of experimentation and collective learning, not disruption. Pair with Failure to Disrupt — the first shows what doesn't work; this shows what might.",
      "personal_notes": null
    },
    {
      "slug": "teaching-machines",
      "collection": "design-ai-learning",
      "title": "Teaching Machines: The History of Personalized Learning",
      "type": "book",
      "url": "https://mitpress.mit.edu/9780262045698/teaching-machines/",
      "authors": ["Audrey Watters"],
      "publisher": "MIT Press",
      "published_date": "2021-01-01",
      "tags": ["edtech-history", "behaviorism", "skeptic"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "A cultural history of 'teaching machines' from Pressey and Skinner through modern software: personalized-learning dreams are a century old. Arms you against the 'this time it's different' AI pitch.",
      "personal_notes": null
    },
    {
      "slug": "co-intelligence",
      "collection": "design-ai-learning",
      "title": "Co-Intelligence: Living and Working with AI",
      "type": "book",
      "url": "https://www.penguinrandomhouse.com/books/741805/co-intelligence-by-ethan-mollick/",
      "authors": ["Ethan Mollick"],
      "publisher": "Portfolio",
      "published_date": "2024-01-01",
      "tags": ["ai-in-education", "optimist", "practical"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "Wharton professor's practical guide to working with LLMs — AI as co-worker, co-teacher, coach — with a substantive education chapter. The most useful single book for thinking pragmatically about AI in learning; pair with skeptical voices.",
      "personal_notes": null
    },
    {
      "slug": "brave-new-words",
      "collection": "design-ai-learning",
      "title": "Brave New Words: How AI Will Revolutionize Education",
      "type": "book",
      "url": "https://www.penguinrandomhouse.com/books/744469/brave-new-words-by-salman-khan/",
      "authors": ["Salman Khan"],
      "publisher": "Viking",
      "published_date": "2024-01-01",
      "tags": ["ai-in-education", "optimist", "tutoring"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The Khan Academy founder's vision for AI tutoring, featuring Khanmigo. Optimistic and concrete; read even if skeptical — this is the vision driving much of the industry investment.",
      "personal_notes": null
    },
    {
      "slug": "machine-learning-and-human-intelligence",
      "collection": "design-ai-learning",
      "title": "Machine Learning and Human Intelligence: The Future of Education for the 21st Century",
      "type": "book",
      "url": "https://www.ucl-ioe-press.com/books/education-policy/machine-learning-and-human-intelligence/",
      "authors": ["Rose Luckin"],
      "publisher": "UCL IOE Press",
      "published_date": "2018-01-01",
      "tags": ["ai-in-education", "academic", "aied"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "UCL professor and long-time AIED researcher on how AI can complement human intelligence in learning. Predates the LLM wave but intellectually serious — a European academic perspective that's neither hype nor doom.",
      "personal_notes": null
    },
    {
      "slug": "artificial-intelligence-in-education-holmes",
      "collection": "design-ai-learning",
      "title": "Artificial Intelligence in Education: Promises and Implications for Teaching and Learning",
      "type": "book",
      "url": "https://curriculumredesign.org/artificial-intelligence-in-education/",
      "authors": ["Wayne Holmes", "Maya Bialik", "Charles Fadel"],
      "publisher": "Center for Curriculum Redesign",
      "published_date": "2019-01-01",
      "tags": ["ai-in-education", "survey", "policy"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Fair-minded, well-sourced survey of AI in education: intelligent tutors, learning analytics, policy implications. The landscape rather than a single argument.",
      "personal_notes": null
    },
    {
      "slug": "critical-ai-in-k12-classrooms",
      "collection": "design-ai-learning",
      "title": "Critical AI in K-12 Classrooms",
      "type": "book",
      "url": "https://hep.gse.harvard.edu/9798895570180/critical-ai-in-k-12-classrooms/",
      "authors": ["Stephanie Smith Budhai", "Marie K. Heath"],
      "publisher": "Harvard Education Press",
      "published_date": "2024-01-01",
      "tags": ["ai-in-education", "skeptic", "equity"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Examines bias, equity, and classroom pedagogy implications of GenAI and LLMs through a critical lens. The who-benefits, who-gets-harmed conversation needs this kind of close reading.",
      "personal_notes": null
    },
    {
      "slug": "ai-snake-oil-book",
      "collection": "design-ai-learning",
      "title": "AI Snake Oil: What Artificial Intelligence Can Do, What It Can't, and How to Tell the Difference",
      "type": "book",
      "url": "https://www.aisnakeoil.com/p/the-book",
      "authors": ["Arvind Narayanan", "Sayash Kapoor"],
      "publisher": "Princeton University Press",
      "published_date": "2024-01-01",
      "tags": ["ai-in-education", "skeptic", "technical"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Princeton computer scientists separate what AI can do from what vendors claim. Not education-specific but essential context — sharpens your ability to read ed-tech marketing critically.",
      "personal_notes": null
    },
    {
      "slug": "one-useful-thing",
      "collection": "design-ai-learning",
      "title": "One Useful Thing",
      "type": "website",
      "url": "https://www.oneusefulthing.org/",
      "authors": ["Ethan Mollick"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["ai-in-education", "optimist", "ongoing", "practical"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "The most-read Substack on practical uses of LLMs: hands-on experiments, prompt examples, teaching reflections. The pragmatic pulse of where LLMs can actually help. Read weekly.",
      "personal_notes": null
    },
    {
      "slug": "cognitive-resonance",
      "collection": "design-ai-learning",
      "title": "Cognitive Resonance",
      "type": "website",
      "url": "https://buildcognitiveresonance.substack.com/",
      "authors": ["Benjamin Riley"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["ai-in-education", "skeptic", "ongoing", "cognitive-science"],
      "status": "unread",
      "is_essential": true,
      "cliff_notes": "Founder of Deans for Impact writes a cognitive-science-grounded critique of AI hype in education. The essential counterweight to Mollick — reading both makes you smart about the actual tradeoffs.",
      "personal_notes": null
    },
    {
      "slug": "willingham-science-and-education-blog",
      "collection": "design-ai-learning",
      "title": "Daniel Willingham — Science & Education Blog",
      "type": "website",
      "url": "https://www.danielwillingham.com/daniel-willingham-science-and-education-blog.html",
      "authors": ["Daniel T. Willingham"],
      "publisher": "danielwillingham.com",
      "published_date": null,
      "tags": ["learning-science", "ongoing", "translation"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The author of Why Don't Students Like School? continues translating cognitive science for practitioners. When a new learning-science study drops, wait for Willingham's take.",
      "personal_notes": null
    },
    {
      "slug": "mathworlds",
      "collection": "design-ai-learning",
      "title": "Mathworlds (dy/dan)",
      "type": "website",
      "url": "https://danmeyer.substack.com/",
      "authors": ["Dan Meyer"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["pedagogy", "math", "skeptic", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Math educator and researcher, influential on problem-based learning and critical of edtech overclaims. Incisive on what actually makes learning stick in math classrooms, including with AI.",
      "personal_notes": null
    },
    {
      "slug": "filling-the-pail",
      "collection": "design-ai-learning",
      "title": "Filling the Pail",
      "type": "website",
      "url": "https://fillingthepail.substack.com/",
      "authors": ["Greg Ashman"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["learning-science", "cognitive-load", "skeptic", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Australian teacher-researcher on explicit instruction, cognitive load, and rigorous ed research. Will call out weak research and wishful thinking — including from progressive and edtech camps.",
      "personal_notes": null
    },
    {
      "slug": "teacherhead",
      "collection": "design-ai-learning",
      "title": "teacherhead",
      "type": "website",
      "url": "https://teacherhead.com/",
      "authors": ["Tom Sherrington"],
      "publisher": "teacherhead.com",
      "published_date": null,
      "tags": ["pedagogy", "practice", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Former UK headteacher, author of Rosenshine's Principles in Action, prolific on pedagogy, curriculum, and classroom craft. Consistently good on the gap between research and classroom reality.",
      "personal_notes": null
    },
    {
      "slug": "second-breakfast",
      "collection": "design-ai-learning",
      "title": "Second Breakfast (and the Hack Education archive)",
      "type": "website",
      "url": "https://2ndbreakfast.audreywatters.com/",
      "authors": ["Audrey Watters"],
      "publisher": "audreywatters.com",
      "published_date": null,
      "tags": ["edtech-history", "skeptic", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Long-time ed-tech historian and critic; the Hack Education archive (2010–2022) is a reference library of ed-tech skepticism. The memory of edtech — essential for not repeating the last hype cycle.",
      "personal_notes": null
    },
    {
      "slug": "minding-the-gap",
      "collection": "design-ai-learning",
      "title": "Minding the Gap",
      "type": "website",
      "url": "https://nataliewexler.substack.com/",
      "authors": ["Natalie Wexler"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["pedagogy", "writing", "literacy", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The author of The Knowledge Gap on literacy, writing instruction, curriculum, and increasingly AI. Especially good on writing pedagogy — the skill most directly affected by LLMs.",
      "personal_notes": null
    },
    {
      "slug": "the-answer-pondiscio",
      "collection": "design-ai-learning",
      "title": "The Answer",
      "type": "website",
      "url": "https://robertpondiscio.substack.com/",
      "authors": ["Robert Pondiscio"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["policy", "knowledge-building", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "AEI fellow and former NYC teacher on curriculum, knowledge, and school reform from a conservative-reformist lens. Strong on the knowledge-building argument and policy realities.",
      "personal_notes": null
    },
    {
      "slug": "larry-cuban-blog",
      "collection": "design-ai-learning",
      "title": "Larry Cuban on School Reform and Classroom Practice",
      "type": "website",
      "url": "https://larrycuban.wordpress.com/",
      "authors": ["Larry Cuban"],
      "publisher": "WordPress",
      "published_date": null,
      "tags": ["edtech-history", "skeptic", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The historian of Teachers and Machines keeps blogging — classroom tech use, reform cycles, and now AI. A living connection to a century of ed-tech history.",
      "personal_notes": null
    },
    {
      "slug": "ai-snake-oil-newsletter",
      "collection": "design-ai-learning",
      "title": "AI Snake Oil (newsletter)",
      "type": "website",
      "url": "https://www.aisnakeoil.com/",
      "authors": ["Arvind Narayanan", "Sayash Kapoor"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["ai-in-education", "skeptic", "technical", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Sober, technically literate critique of AI claims across sectors including education. Helps you separate real LLM capabilities from marketing and evaluate vendor claims.",
      "personal_notes": null
    },
    {
      "slug": "the-biblioracle-recommends",
      "collection": "design-ai-learning",
      "title": "The Biblioracle Recommends",
      "type": "website",
      "url": "https://biblioracle.substack.com/",
      "authors": ["John Warner"],
      "publisher": "Substack",
      "published_date": null,
      "tags": ["writing", "pedagogy", "skeptic", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Writer and writing teacher; author of More Than Words: How to Think About Writing in the Age of AI. Specifically good on the 'should students still learn to write' question.",
      "personal_notes": null
    },
    {
      "slug": "larry-ferlazzo-websites-of-the-day",
      "collection": "design-ai-learning",
      "title": "Larry Ferlazzo's Websites of the Day",
      "type": "website",
      "url": "https://larryferlazzo.edublogs.org/",
      "authors": ["Larry Ferlazzo"],
      "publisher": "Edublogs",
      "published_date": null,
      "tags": ["practice", "aggregation", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Prolific Sacramento teacher-blogger aggregating ESL, classroom practice, and education news, now covering AI regularly. Useful for staying current on practitioner conversations.",
      "personal_notes": null
    },
    {
      "slug": "the-homework-apocalypse",
      "collection": "design-ai-learning",
      "title": "The Homework Apocalypse",
      "type": "article",
      "url": "https://www.oneusefulthing.org/p/the-homework-apocalypse",
      "authors": ["Ethan Mollick"],
      "publisher": "One Useful Thing (Substack)",
      "published_date": "2023-07-01",
      "tags": ["ai-in-education", "assessment", "writing", "optimist"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Most take-home assignments — essays, problem sets, reading summaries — can now be completed by free AI at passing quality, collapsing their assessment value. Sketches three responses: AI-proof assessment, AI-integrated assignments, and rethinking what practice is for.",
      "personal_notes": null
    },
    {
      "slug": "khan-ted-how-ai-could-save-education",
      "collection": "design-ai-learning",
      "title": "How AI Could Save (Not Destroy) Education",
      "type": "video",
      "url": "https://www.ted.com/talks/sal_khan_how_ai_could_save_not_destroy_education",
      "authors": ["Salman Khan"],
      "publisher": "TED",
      "published_date": "2023-05-01",
      "tags": ["ai-in-education", "optimist", "tutoring"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "The Khanmigo vision in 15 minutes: AI as a personal tutor for every student and an assistant for every teacher. Watch as the strongest, most concise version of the optimist case.",
      "personal_notes": null
    },
    {
      "slug": "teachlab-podcast",
      "collection": "design-ai-learning",
      "title": "TeachLab",
      "type": "podcast",
      "url": "https://tsl.mit.edu/teachlab_podcast/",
      "authors": ["Justin Reich"],
      "publisher": "MIT Teaching Systems Lab",
      "published_date": null,
      "tags": ["pedagogy", "edtech-history", "ongoing"],
      "status": "unread",
      "is_essential": false,
      "cliff_notes": "Conversations on teaching, learning, and technology from the MIT Teaching Systems Lab — Reich interviewing researchers and practitioners. Good companion listening to Failure to Disrupt.",
      "personal_notes": null
    }
  ]
}

$seed$::jsonb as data
), resource_rows as (
  select resource
  from seed, jsonb_array_elements(data->'resources') as resource
)
insert into public.resources (
  collection_id, slug, title, type, url, authors, publisher, published_date, tags, status,
  cliff_notes, personal_notes, cover_image_url, source_domain, is_essential
)
select
  collections.id,
  resource->>'slug',
  resource->>'title',
  resource->>'type',
  nullif(resource->>'url', ''),
  coalesce(array(select jsonb_array_elements_text(resource->'authors')), '{}'::text[]),
  nullif(resource->>'publisher', ''),
  case when resource->>'published_date' is null then null else (resource->>'published_date')::date end,
  coalesce(array(select jsonb_array_elements_text(resource->'tags')), '{}'::text[]),
  coalesce(resource->>'status', 'unread'),
  nullif(resource->>'cliff_notes', ''),
  nullif(resource->>'personal_notes', ''),
  nullif(resource->>'cover_image_url', ''),
  case
    when resource->>'url' is null then null
    else regexp_replace((regexp_match(resource->>'url', '^https?://(?:www\.)?([^/]+)'))[1], '^www\.', '')
  end,
  coalesce((resource->>'is_essential')::boolean, false)
from resource_rows
join public.collections on collections.slug = resource->>'collection'
on conflict (slug) do update set
  collection_id = excluded.collection_id,
  title = excluded.title,
  type = excluded.type,
  url = excluded.url,
  authors = excluded.authors,
  publisher = excluded.publisher,
  published_date = excluded.published_date,
  tags = excluded.tags,
  status = excluded.status,
  cliff_notes = excluded.cliff_notes,
  personal_notes = excluded.personal_notes,
  cover_image_url = excluded.cover_image_url,
  source_domain = excluded.source_domain,
  is_essential = excluded.is_essential;

select
  (select count(*) from public.collections) as collections_count,
  (select count(*) from public.resources) as resources_count;
